// import { getGenre } from './js/genresOfMovies';
import { onFirstLoadPage } from './js/onFirstLoadPage';
// import * as searchItems from './js/searchItems';
// import * as createGallery from './js/createGallery';
// import { createNumeration } from './js/createNumeration';
// import * as onSubmitClick from './js/onSubmitClick';
// import * as onPageNumerClick from './js/onPageNumerClick';
// import * as onCardClick from './js/onCardClick';
// import * as onWatchedAndQueueClick from './js/onWatchedAndQueueClick';
// import * as onAddToWatchedAndAddToQueueClick from './js/onAddToWatchedAndAddToQueueClick';
// import * as loader from './js/loader';
import * as modal from './js/modal';